In [1]:
# NIM/Nama: 19622138/Bastian Hendramukti Suryapratama
# Tanggal: 23 November 2022
# Deskripsi: Penyelesaian problem 2

# PROBLEM_2

# KAMUS
# df: dataframe
# filt: series

# ALGORITMA

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("P05-02.csv")

In [4]:
df

,city,area,rooms,bathroom,parking_spaces,floor,animal,furniture,homeowner_tax,rent_amount,property_tax,fire_insurance,total
0,Sao Paulo,70,2,1,1,7,acept,furnished,2065,3300,211,42,5618
1,Sao Paulo,320,4,4,0,20,acept,not furnished,1200,4960,1750,63,7973
2,Porto Alegre,80,1,1,1,6,acept,not furnished,1000,2800,0,41,3841
3,Porto Alegre,51,2,1,0,2,acept,not furnished,270,1112,22,17,1421
4,Sao Paulo,25,1,1,0,1,not acept,not furnished,0,800,25,11,836
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8226,Sao Paulo,150,3,3,2,8,not acept,furnished,0,13500,0,172,13670
8227,Porto Alegre,63,2,1,1,5,not acept,furnished,402,1478,24,22,1926
8228,Sao Paulo,285,4,4,4,17,acept,not furnished,3100,15000,973,191,19260
8229,Rio de Janeiro,70,3,3,0,8,not acept,furnished,980,6000,332,78,7390
8230,Rio de Janeiro,120,2,2,2,8,acept,furnished,1585,12000,279,155,14020

In [8]:
# 1. Banyak rumah yang mengizinkan membawa hewan peliharaan dengan harga sewa per tahun di bawah 5000
filt = (df["animal"] == "acept") & (df["rent_amount"] < 5000)
df.loc[filt].shape[0]

4936

In [19]:
# 2. Data rumah dengan jumlah kamar mandi terbanyak
df.sort_values("bathroom", ascending=0).head(1)

,city,area,rooms,bathroom,parking_spaces,floor,animal,furniture,homeowner_tax,rent_amount,property_tax,fire_insurance,total
319,Sao Paulo,900,4,9,8,1,acept,not furnished,0,15000,5700,226,20930

In [16]:
# 3. Banyak rumah dengan luas di atas 200 dan pajak bangunan per tahun di bawah 1700
filt = (df["area"] > 200) & (df["property_tax"] < 1700)
df.loc[filt].shape[0]

979

In [27]:
# 4. Banyak rumah dengan biaya asuransi kebakaran per tahun di atas 70 untuk masing-masing kota
filt = (df["fire_insurance"] > 70)
df.loc[filt, "city"].value_counts()

Sao Paulo         1095
Rio de Janeiro     196
Belo Horizonte     117
Porto Alegre        48
Campinas            34
Name: city, dtype: int64

In [23]:
# 5. 5 data rumah dengan jumlah lantai terbanyak yang belum dilengkapi furnitur (not furnished)
filt = df["furniture"] == "not furnished"
df.loc[filt].sort_values("floor", ascending=0).head()

,city,area,rooms,bathroom,parking_spaces,floor,animal,furniture,homeowner_tax,rent_amount,property_tax,fire_insurance,total
1936,Belo Horizonte,80,3,2,2,301,acept,not furnished,750,2600,164,35,3549
4392,Campinas,64,2,2,2,51,acept,not furnished,800,1900,129,25,2854
1230,Sao Paulo,353,4,5,5,46,acept,not furnished,3000,10000,0,127,13130
504,Sao Paulo,250,3,2,3,35,acept,not furnished,2500,15000,1084,191,18780
4700,Sao Paulo,84,2,3,2,32,not acept,not furnished,850,8500,450,108,9908